### ISSUE TITLE
3999 and beyond

### ISSUE THREAD

**Issue by pieterdd** [qbunt/romans#30]
Some rulesets allow `M` sequences of more than 3 characters so you can express numbers above 4000. I'm aware that this is not universal, and noticed that romans throws an exception for `'MMMM'`. Is this a conscious design choice?

**Comment by qbunt** [comment]
Hey @pieterdd, yes, it's a conscious design decision. It's an imperfect numbering system for sure, the limit is in place because it's the closest I can find to a universal max value. Believe it or not someone posted another issue that they could go over 4,000 so now I run unit tests against that max.

If you have a use-case for it, I'm sure there's a way I could support exceeding that limit, also open to PRs to support it too. Thanks for filing the issue!

**Comment by pieterdd** [comment]
This answers my question, thanks qbunt!
